title: "Homeschooling Success: A Korean-Australian Perspective"
author:                           # 작성자 정보
  name: "Cornelius"                 # 작성자 이름
  email: "seinlim@gmail.com"        # 작성자 이메일
  bio: "Cornelius is a lifelong learner, avid traveler, and dedicated parent on a mission to empower families through education and exploration. His blog chronicles their homeschooling journey in Australia, sharing insights, experiences, and resources on topics ranging from coding and cooking to mindful living and cultural immersion."

description: >-                   # 블로그 설명 (여러 줄 가능)
  "A personal blog documenting my journey through the world of code, parenting, faith, books, baking, homeschooling, and the joys of raising young boy."

baseurl: "/"                     # 깃허브 페이지 저장소 이름과 일치 (보통 "/")
url: "https://fromatoz.github.io"  # 실제 깃허브 페이지 URL

# 깃허브 정보
github_username: Coryian       # 깃허브 사용자 이름

# 테마 설정
theme: minima                   # 사용할 Jekyll 테마 (Minima)
