# Site Settings
title: "A Family's Guide to Homeschooling and Life in Australia"
author:
  name: Cornelius
  email: seinlim@gmail.com
  bio: "Cornelius is a lifelong learner, avid traveler, and dedicated parent on a mission to empower families through education and exploration. His blog chronicles his family's homeschooling journey in Australia, sharing insights, experiences, and resources on topics ranging from coding and cooking to mindful living and cultural immersion."
description: "A personal blog documenting our family's journey through the world of code, parenting, faith, books, baking, homeschooling, and the joys of raising young boys in Australia."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://coryian.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social Media (Optional)
# Add your social media usernames if you want them displayed on your site
twitter_username: 
instagram_username: 
github_username: Coryian

# Build Settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown Processor Settings (Optional)
# Configure your preferred markdown processor and extensions
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Collections (Optional)
# Define custom collections for organizing your content
collections:
  recipes:
    output: true
  travel:
    output: true

# Defaults for Posts (Optional)
# Set default values for frontmatter in your posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      share: true

# Pagination (Optional)
# Configure pagination for your blog posts
paginate: 5
paginate_path: "/page:num/"
